sudo: required
language: java
before_install: 
  - chmod +x mvnw
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
script: mvn package
services: 
  - docker
after_success:
  - heroku container:login
  - heroku container:push web --app=test-iot-platform
  - heroku container:release web --app=test-iot-platform