sudo: required
language: java
install: true
before_install: 
  - chmod +x mvnw
script: mvn package
services: 
  - docker
after_success:
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  - docker build -t registry.heroku.com/test-iot-platform/web -f Dockerfile .
  - docker push registry.heroku.com/test-iot-platform/web
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - heroku container:release web --app $HEROKU_APPLICATION