sudo: required
language: java
before_install: 
  - chmod +x mvnw
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
script: mvn package
services: 
  - docker
after_success:
  - heroku container:login
  - heroku container:push web --app $HEROKU_APPLICATION
  - heroku container:release web --app $HEROKU_APPLICATION