sudo: required
language: java
install: true
before_install: 
  - chmod +x mvnw
script: mvn package
services: 
  - docker
after_success:
  - mvn docker:build
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker push shchipunov/iot-platform
  - test “$TRAVIS_BRANCH” = “master” && sh heroku.sh