sudo: required
language: java
before_install: 
  - docker build -t shchipunov/iot-platform .
script: mvn test -B
services: 
  - docker
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
after_success:
  - test “$TRAVIS_BRANCH” = “master” && sh heroku.sh