sudo: required
language: java
before_install: 
  - chmod +x mvnw
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com
script: mvn package
services: 
  - docker
after_success:
  - heroku container:login
  - heroku container:push web --app test-iot-platform
  - heroku container:release web --app test-iot-platform
  - heroku run bash --app test-iot-platform
  - heroku open --app test-iot-platform