sudo: required
language: java
before_install: 
  - chmod +x mvnw
script: mvn test -B
services: 
  - docker
before_deploy: 
  - docker build -t shchipunov/iot-platform .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
after_deploy:
  - test “$TRAVIS_BRANCH” = “master” && sh heroku.sh