sudo: required
language: java
before_install: 
  - chmod +x mvnw
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
script: mvn package
services: 
  - docker
after_success:
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  - docker build -t registry.heroku.com/test-iot-platform/web -f Dockerfile .
  - docker push registry.heroku.com/test-iot-platform/web
  - heroku container:login
  - heroku container:release web