sudo: required
language: java
install: true
before_install: 
  - chmod +x mvnw
script: mvn package
services: 
  - docker
after_success:
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  - docker build -t registry.heroku.com/test-iot-platform/web -f Dockerfile .
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APPLICATION